version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://db:27017
      - MONGO_DB=2024DcardBackend
      - MONGO_COLLECTION=ads
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - db
      - redis
  db:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"